### ISSUE TITLE
Duplicate rendering

### ISSUE THREAD

**Issue by wdjunaidi** [KanbanSolutions/jquery-tmpl#1]
I'm writing simple test using {%each%} tag inside table to display row for each data. The output render the properly, however it also repeat the rendering of the table same amount of times as the row of data.

The test case as simple as following:

``` html
<script id="testTemplate" type="x-jquery-tmpl">
  <table>
    <thead>
      <tr>
        <th>No</th><th>Title</th><th>Authors</th>
      </tr>
    </thead>
    <tbody>
    {%each(index,book) books %}
      <tr>
        <td>{%= index + 1 %}</td>
        <td>{%= book.title %}</td>
        <td>{%= book.authors %}</td>
      </tr>
    {%/each%}
    </tbody>
  </table>
</script>
<script>
  var books = [ 
      { "title":"Book One", "authors":"First Author"}, 
      {"title":"Book Two", "authors":"Second Author"} 
    ];
  $("testTemplate").tmpl(books).appendTo("#putHere");
</script>
```

The sample above give me 2 identical tables on screen.

**Comment by wdjunaidi** [comment]
I'm pretty sure it is defect with the template rendering engine, I did the same think with twitter-bootstrap navigation tabs and I got twice the amount of tabs on my screen.
![Capture](https://f.cloud.github.com/assets/1240283/178718/88cd487a-7bc8-11e2-876b-bdaab93b8314.PNG)

**Comment by djgilcrease** [comment]
I think it is because how you are passing the data it should be .tmpl({books:books})

**Comment by wdjunaidi** [comment]
Any plan on updating the documentation? I'm learning mostly based on the original jquery-tmpl examples, with that project abandoned and this project changing syntax. It is better to have it's own documentation.

Thanks

**Comment by djgilcrease** [comment]
Yes. I do plan to update the documentation, though nothing fundamental has changed other than switching to {%%} instead of {{}}. The Javascript API and method calls are all the same.
